### ISSUE TITLE
bundles/common_models won't build with master-19.06

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#16]
I am not sure what the policy should be when reporting compatibility issues with the rock-osdeps. I guess it is not the target of this software to keep compatibility with all other packages at master. On the other hand, there are also no guidelines on what *should* be compatible. Is there a policy therefore on what should be reported?

```
Autobuild::Ruby:bundles/common_models:post-install: WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment variable is deprecated
Autobuild::Ruby:bundles/common_models:post-install: WARN: just put a file called typelib_plugin.rb into a subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
Autobuild::Ruby:bundles/common_models:post-install: WARN: offending dir: /opt/rock/master-19.06/share/typelib/ruby
Autobuild::Ruby:bundles/common_models:post-install: rake aborted!
Autobuild::Ruby:bundles/common_models:post-install: NoMethodError: undefined method `define_rubocop_if_enabled' for Roby::App::Rake:Module
Autobuild::Ruby:bundles/common_models:post-install: Did you mean?  define_or_reuse
Autobuild::Ruby:bundles/common_models:post-install: /opt/workspace/bundles/common_models/Rakefile:31:in `<top (required)>'
Autobuild::Ruby:bundles/common_models:post-install: /home/devel/.local/share/autoproj/gems/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Autobuild::Ruby:bundles/common_models:post-install: (See full trace by running task with --trace)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
  ERROR: 1 packages failed: bundles/common_models
```

It can be avoided with this override:

```bash
  - bundles/common_models:
    branch: master
    commit: 8a0ac734
```

**Comment by Rauldg** [comment]
Actually, this issue is maybe unrelated to the rock-osdeps.

**Comment by doudou** [comment]
`common_models` being part of rock-core, the only guarantee is that the version shipped with a given release works with the rock-osdeps of the same release. There is no guarantee beyond that (so far).

I'm trying to find some time to start versioning this stuff, in which case we'd be using semantic versioning. But this won't even help you in this particular case: this is a case of a new version requiring a new version of another package, which is fair game as long as both don't increase their major version

**Comment by Rauldg** [comment]
If I understand it right, this means that the *guarantee* reaches only the packages that are part of the release. Makes sense. 

Would not be helpful to have some short of register with later compatible versions of the packages? It is very common to have to blacklist something, and people going through that process could somehow save some time of other people by somehow (ideally automatically) uploading their success/failure stories somewhere. Not sure if issues is the most efficient way to register that info.

**Comment by doudou** [comment]
> Would not be helpful to have some short of register with later compatible versions of the packages?

I would think so, yes.

I'm living on master, so not so interested. But I think it would be welcome.
